name: Conventional Commits

on:
  pull_request:
    branches: [ main ]
  push :

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: agenthunt/conventional-commit-checker-action@v2.0.0


