name: Conventional Commits

on:
  pull_request:
    branches: [ main ]
  push :

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: webiny/action-conventional-commits@v2.0.0


